### ISSUE TITLE
feat: add profile/alias for remote workspace

### ISSUE THREAD

**Issue by wey-gu** [yihong0618/rcode#3]
like `rcode myFancySideProjectFoo` or other syntax?

The conf could be yaml/toml based? and support `list` and `add`, `delete`?

If it looks good, I could contribute this as I will be its user.

**Comment by yihong0618** [comment]
Of course ~
gogogo

**Comment by yihong0618** [comment]
we can add 
```
rcode latest
```
just open last rcode dir

**Comment by yihong0618** [comment]
added
```
rcode -l or rcode --latest
```

**Comment by wey-gu** [comment]
> added
> 
> ```
> 
> rcode -l or rcode --latest
> 
> ```

omg 🧎

**Comment by yihong0618** [comment]
@wey-gu 
done
```
add shortcut_name rcode s ~/abc -sn abc then you can use rcode -os abc to open this dir quickly
```
